name: 🐞 버그 제보
description: 서비스 운영 중 발생한 버그를 제보해주세요
title: "[Bug] "
labels:
  - "bug"
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        **버그 제보를 위한 이슈입니다. 발생한 버그에 대한 간단한 설명과 재현 방법을 기록해주세요.**
  - type: textarea
    id: bug-description
    attributes:
      label: 버그 설명
      description: 발생한 버그에 대한 설명을 적어주세요
      placeholder: 발생한 버그에 대한 설명을 적어주세요
      value: |
        <!-- 발생한 버그에 대한 상세 설명을 적어주세요 -->
    validations:
      required: true
  - type: textarea
    id: bug-reproduction
    attributes:
      label: 재현 방법
      description: 발생한 버그를 재현할 수 있는 방법을 적어주세요
      placeholder: 발생한 버그를 재현할 수 있는 방법을 적어주세요
      value: |
        <!-- 발생한 버그를 재현할 수 있는 방법을 적어주세요 -->
  - type: textarea
    id: bug-screen-shot
    attributes:
      label: 스크린샷
      description: 발생한 버그에 대한 스크린샷을 첨부해주세요
      placeholder: 발생한 버그에 대한 스크린샷을 첨부해주세요
      value: |
        <!-- 발생한 버그에 대한 스크린샷을 첨부해주세요 -->
  - type: dropdown
    id: browsers
    attributes:
      label: 브라우저 환경
      multiple: true
      options:
        - Chrome
        - Safari
        - Android
        - IOS
        - In App Browser
