name: 🐞 버그 제보
description: 서비스 이용 중 발생한 버그를 제보해주세요
title: "[Bug] : "
labels: ["bug"]
assignees:
  - 
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 버그 제보
      description: 발생한 버그에 대한 설명을 적어주세요
      placeholder: 발생한 버그에 대한 설명을 적어주세요
      value: |
        ## 상세 설명
        <!-- 발생한 버그에 대한 상세 설명을 적어주세요 -->

        ## 재현 방법
        <!-- 발생한 버그를 재현할 수 있는 방법을 적어주세요 -->

        ## 스크린샷
        <!-- 발생한 버그에 대한 스크린샷을 첨부해주세요 -->
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: 브라우저 환경
      multiple: true
      options:
        - Chrome
        - Safari
        - Android
        - IOS
        - In App Browser
