name: 🐞 버그 제보
description: 버그 제보
title: "[Bug] : "
labels: ["bug"]
assignees:
  - 
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 버그 제보
      description: 발생한 버그에 대한 설명을 적어주세요
      placeholder: 발생한 버그에 대한 설명을 적어주세요
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: 브라우저 환경
      multiple: true
      options:
        - Chrome
        - Safari
        - Android
        - IOS
        - In App Browser
