name: 🛠️ 기능 구현
description: 기능 구현
title: "[Feature] : "
labels: ["feature"]
assignees:
  - 
body:
  - type: textarea
    attributes:
      label: 기능 제안
      description: 기능에 대한 설명을 적어주세요
      placeholder: 기능에 대한 설명을 적어주세요
    validations:
      required: true
